### ISSUE TITLE
how to design svg contribution

### ISSUE THREAD

**Issue by krishan-here** [pranavmadhu01/pranavmadhu01#1]
hey i want to show this 3d view of contribution in my profile.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/82387829/188266889-b89d20d6-b6a9-4201-8dd2-a5b7024a8970.png">

but don't understand the code properly. Can you please help me?

**Comment by pranavmadhu01** [comment]
yes sure,
head on to [metrics](https://metrics.lecoq.io/)->**enter your username** -> **pick the necessary features** -> **copy the markdown code and paste it on to the README.md of your github profile**. We also need **action code** present aside of markdown code.
In your **github** go to the **settings** -> **developer settings** -> **create a personal access token**.
In your **repository** go to **settings** -> **secrets** -> **create a new secret**  with the access token created name it with **METRICS_TOKEN**.
In your **repository** go to **actions** -> **create a new workflow** -> **paste the action code** -> **wait for the workflow run** -> **see the results**.
